#!/usr/bin/env bash
# scripts/audit/manifest-parity.sh — Family 2 of /audit.
#
# v1 scope: MCP tool permission parity between Claude and Auggie configures.
# The `mcp__gvrn__*` entries are deterministically generated by
# scripts/gen-configure-mcp.sh from framework/runtime-tools.txt and must
# be in perfect agreement across both agent files. A drift here means
# either the generator failed silently or someone hand-edited a configure
# file. High-signal, zero-noise.
#
# Out of v1 scope (deferred to follow-on scenarios):
#
#   * Installer file list (govern.md ↔ init.md). init.md is hand-
#     maintained at .claude/commands/gov/init.md only — there's no
#     framework/commands/init.md source to diff against. The two
#     installer paths describe scaffolding in different prose shapes;
#     comparing them needs structured manifests rather than regex
#     extraction. See 026 plan §Known limitations.
#
#   * Non-MCP permission parity (Bash↔launch-process, Edit↔str-replace-editor,
#     Write↔save-file, view↔Read, grep-search↔Grep, etc.). The Claude
#     permission set is intentionally broader than Auggie's in several
#     places (different hook integration, different fallback paths); a
#     literal diff produces high false-positive noise. Needs a hand-
#     maintained tool-name correspondence table — captured for a future
#     scenario after `/audit` v1 has been live and the desired tightness
#     emerges from real maintenance experience.

set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

drift=0

emit() {
  echo "manifest-parity | $1 | $2 | $3"
  drift=1
}

# Extract the set of MCP tool names from each agent's configure file,
# stripping the agent-specific prefix so the sets are directly comparable.
# Claude uses `mcp__gvrn__name` (double-underscore); Auggie uses
# `mcp:gvrn:name` (colon). Normalize both to just the bare tool name
# (e.g., `read-spec`, `mark-task`).
extract_claude_mcp() {
  local file="$1"
  grep -oE '`mcp__gvrn__[a-z-]+`' "$file" \
    | tr -d '`' \
    | sed -E 's/^mcp__gvrn__//' \
    | sort -u
}

extract_auggie_mcp() {
  local file="$1"
  grep -oE '"toolName": *"mcp:gvrn:[a-z-]+"' "$file" \
    | sed -E 's/.*"mcp:gvrn:([a-z-]+)".*/\1/' \
    | sort -u
}

claude_mcp="$(extract_claude_mcp "framework/bootstrap/configure/claude.md")"
auggie_mcp="$(extract_auggie_mcp "framework/bootstrap/configure/auggie.md")"

only_claude="$(comm -23 <(printf '%s' "$claude_mcp") <(printf '%s' "$auggie_mcp"))"
only_auggie="$(comm -13 <(printf '%s' "$claude_mcp") <(printf '%s' "$auggie_mcp"))"

if [ -n "$only_claude" ]; then
  while IFS= read -r entry; do
    [ -z "$entry" ] && continue
    emit "framework/bootstrap/configure/auggie.md" "MCP permission only in Claude config: $entry" "re-run scripts/gen-configure-mcp.sh to resync the generated blocks"
  done <<< "$only_claude"
fi
if [ -n "$only_auggie" ]; then
  while IFS= read -r entry; do
    [ -z "$entry" ] && continue
    emit "framework/bootstrap/configure/claude.md" "MCP permission only in Auggie config: $entry" "re-run scripts/gen-configure-mcp.sh to resync the generated blocks"
  done <<< "$only_auggie"
fi

exit "$drift"
